### PR TITLE
Major changes described bellow

### PR DESCRIPTION
**Pull request by miroslavKovacPantheon**
Change code according to new plotform-implementation-metadata
yang module. Change platform-metadata.json files too.

Fix search-filter post request to check for wrong data

Change setup file to find packages automaticaly

Add to automatic pull request and merge check for
commit_msg sha so it will allow to merge only files sent by
automatic ietf downloads.

Resolve netconf-capabilities received from api or
platform-metadata.json files

Create api request for getting specific leaf only
like email for filtered request

Fix bugs

Parse semantic version

Parse derived semantic version

get rid of missing element values

Signed-off-by: miroslav.kovac <miroslav.kovac@pantheon.tech>

### CODE REVIEW

**Comment by tnadeauaria** [comment]
When pushing a PR in the future, please assign it to one of the committers (Carl, Einar or myself).  That will expedite the PR approval process. Thanks!

**Comment by miroslavKovacPantheon** [comment]
I tired to assign but I didn t find that option anywhere..

**Comment by tnadeau** [comment]
If you look at the top right, there should be a “Request a Review” shown like this:

**Comment by miroslavKovacPantheon** [comment]
I signed in as a yang-catalog user to check other PR there is and to try assign but this is a print screen of what I see ->
prtscn

**Comment by tnadeau** [comment]
That is odd. I thought that you could request reviews upon pushing a PR.  I just verified that this is not the case.  Pfft. :(

	—Tom

**Pull request merged**
