### PR TITLE
corrected with new native yang model name in README.md

### PR DESCRIPTION
**Pull request by kyoungyun**
corrected with new native yang model name in README.md

### CODE REVIEW

**Comment by kyoungyun** [comment]
Hi.
Any reason why this pull request is not getting merged?

Thank you.

Kyoung

**Comment by tnadeau** [comment]
I’ve asked to include the changes needed for the travis CI.  We
do not push any code to the repo unless its tested as part of the automated
CI process.

	—Tom

**Comment by kyoungyun** [comment]
When and how did you ask me to include the travis CI run result?  I cannot find any message from you.  In any case, The travis CI run result is shown right on this pull request and it says it passed.  Why isn't this good enough?

**Comment by tnadeau** [comment]
Sorry there is another merge request pending and I thought this was related to it.

**Pull request merged**
