### PR TITLE
General 802.1Qcp D1.0 YANG module fixes

### PR DESCRIPTION
**Pull request by MarcHolness**
mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1ax.yang
pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-types.yang
pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-bridge.yang
pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-tpmr.yang
pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-vlan-bridge.yang
pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-pb.yang
ieee802-dot1ax.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1ax"

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1x.yang
ieee802-dot1x.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1x"

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-types.yang
ieee802-dot1q-types.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-types"

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-bridge.yang
ieee802-dot1q-bridge.yang:1: warning: IETF rule (RFC 6087: 4.9): too many top-level data nodes: bridges, bridges-state
ieee802-dot1q-bridge.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-bridge"

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-tpmr.yang
ieee802-dot1q-tpmr.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-tpmr"

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-vlan-bridge.yang
ieee802-dot1q-vlan-bridge.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-vlan-bridge"

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-pb.yang
ieee802-dot1q-pb.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-pb"

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master)
$

### CODE REVIEW

**Comment by einarnn** [comment]
Marc,

Could you resolve the conflicts prior to submission of the pull request? It looks like, from the first file I looked in, that they may be whitespace issues. Also I notes that the changes mention 'd-bride-component' in constraint statements. I can't help but think that 'bride' should perhaps be 'bridge'?

Cheers,

Einar

**Comment by MarcHolness** [comment]
Hi Einar,

Is there some way I can back out the previous pending submissions. I have submitted/committed a new change request. The commit id is bd440c9.

Marc.

**Comment by einarnn** [comment]
Marc,

I don't see any outstanding pull requests. I closed the one you submitted before that had conflicts and possible typos as I noted.

Have you submitted another pull request?

Cheers,

Einar

**Comment by MarcHolness** [comment]
Hi Einar,

I believe I have submitted another pull request. I believe the title is “Commit bd440c9 - 802.1Qcp and 802.1Xck comment resolution  #134”.

Marc.

**Comment by einarnn** [comment]
Yes, that just came in. Again, there are a whole bunch of merge conflicts with what is on the YangModels/yang master. Could you resolve these by first pulling from the YangModels/yang repository to your fork, and address the conflicts before we try to take the commit onto YangModels/yang? Otherwise someone like me will have to work out how to resolve those merge conflicts, and I , as an example, am not so familiar with your models.

Cheers,

Einar

**Comment by MarcHolness** [comment]
Einar,

Thanks for your help and guidance.

I’m such a neophyte at using GitHub.

  *   When you say I need to “first pull from the YangModels/yang repository to your fork”. How do I do this?
  *   How do I see the conflicts?

Sorry for the stupid questions.

Marc.

**Comment by einarnn** [comment]
Marc,

Sorry for the delay, I’ve been away on holiday! :-)

Take a look at:

https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

This details the basic process. In your case you would run the command:

git pull https://github.com/YangModels/yang.git master

…and then review the merge conflicts.

Cheers,

Einar

--
Einar Nilsen-Nygaard

**Comment by MarcHolness** [comment]
Hi Einar,

Firstly, thanks for all your help.

I think I have now resolved my merger conflicts. I followed the instructions at https://help.github.com/articles/resolving-a-merge-conflict-on-github/. I have also committed the changes.

However, I think I have messed something up. Now, when I open my “Git Bash”, I see (YangModels/master |MERGING). Should I be concerned about this?

In addition, when I compile my modules, I get the following output:

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master|MERGING)
$ clear

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master|MERGING)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1ax.yang
ieee802-dot1ax.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1ax"
C:\Users\mholness\Documents\GitHub\yang\standard\ietf\RFC\ietf-yang-types.yang:1: error: syntax error: expected separator, got: "@2013-..."

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master|MERGING)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1x.yang
ieee802-dot1x.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1x"
C:\Users\mholness\Documents\GitHub\yang\standard\ietf\RFC\ietf-inet-types.yang:1: error: syntax error: expected separator, got: "@2013-..."
C:\Users\mholness\Documents\GitHub\yang\standard\ietf\RFC\ietf-yang-types.yang:1: error: syntax error: expected separator, got: "@2013-..."

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master|MERGING)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-types.yang
ieee802-dot1q-types.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-types"
C:\Users\mholness\Documents\GitHub\yang\standard\ietf\RFC\ietf-yang-types.yang:1: error: syntax error: expected separator, got: "@2013-..."

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master|MERGING)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-bridge.yang
ieee802-dot1q-bridge.yang:1: warning: IETF rule (RFC 6087: 4.9): too many top-level data nodes: bridges, bridges-state
ieee802-dot1q-bridge.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-bridge"
C:\Users\mholness\Documents\GitHub\yang\standard\ietf\RFC\ietf-yang-types.yang:1: error: syntax error: expected separator, got: "@2013-..."

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master|MERGING)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-tpmr.yang
ieee802-dot1q-tpmr.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-tpmr"
C:\Users\mholness\Documents\GitHub\yang\standard\ietf\RFC\ietf-yang-types.yang:1: error: syntax error: expected separator, got: "@2013-..."

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master|MERGING)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-vlan-bridge.yang
ieee802-dot1q-vlan-bridge.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-vlan-bridge"

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master|MERGING)
$ pyang --ietf -p $HOME/Documents/GitHub/yang/standard/ietf/RFC:$HOME/Documents/GitHub/yang/standard/ieee/draft ieee802-dot1q-pb.yang
ieee802-dot1q-pb.yang:3: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-pb"
C:\Users\mholness\Documents\GitHub\yang\standard\ietf\RFC\ietf-yang-types.yang:1: error: syntax error: expected separator, got: "@2013-..."

mholness@ONW-MHOLNESS-01 MINGW64 ~/Documents/GitHub/yang/standard/ieee/802.1/draft (YangModels/master|MERGING)
$

I think the problem is that I am referencing an older version of ietf-yang-types.yang and ietf-inet-types.yang. How should I resolve this?

Best Regards,

Marc.

**Comment by einarnn** [comment]
Marc,

Sorry for slow reply. With respect to your MERGING prompt, this may give you some insights:

http://stackoverflow.com/questions/11646107/you-have-not-concluded-your-merge-merge-head-exists

I’m afraid this is not a problem I have seen myself, and I don’t use windows for anything except updating Outlook server-side rules ;-)

With respect to the pyang errors, you may be experiencing a windows effect. The file ietf-yang-types.yang is set in git as a symbolic link to a different file, ietf-yang-types@2013-07-15.yang, but it looks like this is not working as expected. Been a long time since I used windows daily, but when I was a user, it didn’t have symlinks at all, so this may be causing a problem. Suggest looking at this further.

Cheers,

Einar

**Comment by MarcHolness** [comment]
Thanks Einar.

I issued a git merge –abort command and everything seems to have cleared up.

Thanks,

Marc.

**Pull request closed without merging**
