### PR TITLE
pdating script according to new yang catalog

### PR DESCRIPTION
**Pull request by miroslavKovacPantheon**
Populating of yangdatabase is faster and is done with two requests
rather than with a request per each yang file. Prepare script will
create a json file that will be able to populate the database

yangIntegrity script is made for Einar to be able to see which files
and submodules are missing which are extra and also he will see missing
or wrong namespace, revision.

runCapabilites and statistics script creates some basic statistics but
this is still to be done together with statisticsInCatalog scritp.
We need to pull the statistics code from runCapabilites and move it to
statisticsInCatalog.

Script will also check if there was any change on capability.xml file
and if not we will not parse that folder.

Signed-off-by: miroslav.kovac <miroslav.kovac@pantheon.tech>

### CODE REVIEW

**Comment by tnadeau** [comment]
Can you update the documentation for developers updating files to
include how to update the JSON file?

	—Tom

**Comment by miroslavKovacPantheon** [comment]
Hi Tom,

This will be done via APIs and unfortunately they are not done yet. They are in progress. The populate script will parse and populate yangcatalog only with data that are in vendor folder of this project.

Regards,
Miroslav Kovac

**Comment by tnadeau** [comment]
That is cool. Can you open an issue to track this if you won’t have time
to do it fairly soon?  That way we won’t loose the thread.
	
	Thx,

	—Tom

**Comment by miroslavKovacPantheon** [comment]
Sounds reasonable. Done in here https://github.com/YangModels/yang/issues/162 .

Regards,
Miroslav Kovac

**Comment by tnadeau** [comment]
cheers

**Pull request merged**
