### PR TITLE
Major changes described bellow

### PR DESCRIPTION
**Pull request by miroslavKovacPantheon**
Create api webhook to check for new or updated
platform-metadata.json files

Create api to compare derrived semantic version
of two different implementations

Fix bugs

Create trigger in api for IETF files pull

Update config.ini file

Add saving yang files to local directory

Change some http requests from http library to
requests library

Signed-off-by: miroslav.kovac <miroslav.kovac@pantheon.tech>

### CODE REVIEW

**Comment by miroslavKovacPantheon** [comment]
Hi, @tnadeau 

Would there be a way somehow for me to create a request for a review from Einar or you? I really wouldn't like to bother you guys with messages or emails for that.. 

Thank you

**Comment by einarnn** [comment]
PR notifications are now going to a slack room as well as emailed notifications. We can try to be more responsive.

**Comment by tnadeau** [comment]
I’ve checked, and there doesnt seem to be a way to do this explicitly unless you are
a committer. However, since you have commit rights now, you can select that. Its the little
gear icon on the top right of the PR. Just pull it down and select one of us two (or both).

	—Tom

**Comment by einarnn** [comment]
Miroslav’s day to day userid isn’t a committee right now (unless you added him?), just “yang-Catalog”, which we want to only deal with it’s own sandbox, not general issues (IMO).

**Comment by tnadeau** [comment]
Oh sorry. Thought Miroslav was referring to yang-catalogue!

	Well, another approach is to login as yang-catalogue and set the reviewers that way. 8)

	BTW, please never review your own PRs; that is why we have multiple committers. 8)

	—Tom

**Comment by miroslavKovacPantheon** [comment]
I would never set myself as a reviewer. I would set only you guys.. But Ok I could use yang-catalog user for setting review.. 

Thank you

**Comment by tnadeau** [comment]
Perfecto!

**Pull request merged**
