### PR TITLE
Clarification on applicability

### PR DESCRIPTION
**Pull request by cmoberg**
As discussed with Dean, brief note on applicability of model types.

### CODE REVIEW

**Comment by tnadeau** [comment]
can you please post the output from the run of pyang to ensure things still compile?

**Comment by cmoberg** [comment]
Not sure exactly what you mean, as there is no content for pyang in there.

**Comment by ivandean** [comment]
Tom,

There is no Yang model in this draft

Dean

**Comment by tnadeau** [comment]
Oh sorry - I just looked at the diffs in detail. Its an XML file! *)

**Pull request merged**
