### PR TITLE
Updated modules in D2.1

### PR DESCRIPTION
**Pull request by yanzhuang**

### CODE REVIEW

**Comment by tnadeau** [comment]
Please rebase your branch so that merging can be done automatically. I am going to close this PR so that you can rebase and push an updated PR.

**Comment by tnadeau** [comment]
No, I mean “git rebase” - which is to say, re-sync the fork/branch on which you were developing with the master branch.
For example:

https://git-scm.com/book/en/v2/Git-Branching-Rebasing <https://git-scm.com/book/en/v2/Git-Branching-Rebasing>

	—Tom

**Comment by yanzhuang** [comment]
Hi Tom...thank you for this. The problem is I cannot install git on the computer and can only use the webpage PR...Will rebase also apply in browser updates?

**Comment by tnadeau** [comment]
It doesn’t really matter which interface you use (CLI or web). Your forked branch you created is out of date.  Honestly in your situation, the easiest thing to do is to save off your diffs, destroy the forked branch you created, create a new one, then re-modify your files and push a new PR.

	—Tom

**Comment by yanzhuang** [comment]
thank you! will do it right now.

**Comment by yanzhuang** [comment]
Hi Tom, I used a new fork and push a PR while it still asks for review and cannot perform merging automatically.

**Comment by tnadeau** [comment]
All P-Rs require at least 1 review from a committer; thats just the repo’s policy.

	I just merged.  

	Thanks!

	—Tom

**Comment by yanzhuang** [comment]
Tom, thank you very much for the guidance and help~

**Pull request closed without merging**
