### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by samans**
Fixed an import
Replace augment to bridge with a reference.

### CODE REVIEW

**Comment by samans** [comment]
Sorry if I didn't do something.  What would need to be done to the check.sh
script?  The one I see just loops over all yang files in the directory.

**Comment by tnadeau** [comment]
That is precisely the file you need to modify. Use it as a template if you need to create a new one, but I suspect all you need to do is modify it to include your new file.  When you do that, run it locally as a test before you redo your PR.  

	Its these unattended tests that keep the repo’s quality at a decent level, which is why we insist these are done.

	—Tom

**Comment by samans** [comment]
Sorry I must be being dense.  I don't understand what I need to do.  When I
look in check.sh it loops over all files in the directory, it doesn't have
a list of files.  It does a:

"for f in *.yang do" kind of loop.  When I run check.sh locally it picks up
my file.  So, what do I need to modify?

thanks,
-scott.


On Tue, Jan 23, 2018 at 10:27 AM, thomas d. nadeau <notifications@github.com
> wrote:

>
> That is precisely the file you need to modify. Use it as a template if you
> need to create a new one, but I suspect all you need to do is modify it to
> include your new file. When you do that, run it locally as a test before
> you redo your PR.
>
> Its these unattended tests that keep the repo’s quality at a decent level,
> which is why we insist these are done.
>
> —Tom
>
>

**Comment by tnadeau** [comment]
Sorry for the delay.

	If it does, that is fine. Its just up to you to verify that it is actually testing the file you are pushing.

	—Tom

**Comment by samans** [comment]
No problem.  I'm doing it again.  I have started from a fresh fork and am
following your directions (I talked with Marc Holness).  Hopefully my next
pull request will be done correctly.

thanks for your patience.

regards,
-scott.

On Thu, Jan 25, 2018 at 10:31 AM, thomas d. nadeau <notifications@github.com
> wrote:

>
> Sorry for the delay.
>
> If it does, that is fine. Its just up to you to verify that it is actually
> testing the file you are pushing.
>
> —Tom
>
>
>

**Comment by tnadeau** [comment]
Cool. Please do not hesitate to reach out if you need help. Im around/available
for the rest of today/Friday.  Also note that we have a Slack channel, so you can 
also discuss there and perhaps get quicker answers:

https://yangmodels.slack.com/messages/C0QF8LPEC <https://yangmodels.slack.com/messages/C0QF8LPEC>

	Cheers,

	—Tom

**Pull request closed without merging**
