### PR TITLE
modules in D1.2

### PR DESCRIPTION
**Pull request by yanzhuang**
Updated after IEE 802.3 September interim meeting

### CODE REVIEW

**Comment by MarcHolness** [comment]
Changes are primarily editorial in nature.

- Please remove **ieee802-ethernet-link-oam.txt** and **ieee802-ethernet-interface-legacy.txt** files from patch. They do not appear to be YANG modules that are apart of the "official" 802.3 project.

**Comment by yanzhuang** [comment]
Thank you very much for the review~
The thing is we do have tree hierarchies for each modules in the draft and yes, it is not modules.
Do you want to remove all tree files?

**Comment by tnadeau** [comment]
Yes, please do. The tree files can be easily generated using pyang and other tools, so there is no need to store them.

	Thanks!

	—Tom

**Comment by yanzhuang** [comment]
done.

**Pull request merged**
