### PR TITLE
yc.o sync

### PR DESCRIPTION
**Pull request by xorrkaz**
I'm going to try and flush these commits once more after this merge.

### CODE REVIEW

**Comment by einarnn** [comment]
@xorrkaz, do we expect a fix for the breakage sometime soon?

**Comment by xorrkaz** [comment]
Is that breakage me or bbf?

**Comment by einarnn** [comment]
> Is that breakage me or bbf?

Looking at the details now, it's the BBF. Will approve yours.

@wlupton, is there a timeline on addressing the breakages in your models?

Thanks!

**Comment by wlupton** [comment]
> @wlupton, is there a timeline on addressing the breakages in your models?

It's outside our control (the problem is a missing ITU-T module). This is discussed in PR #1596 (actually I didn't expect you to merge that until the problem was resolved), which notes that @jboyd77 has been in contact with @samans about this

**Comment by samans** [comment]
We have a meeting next week where we will discuss providing the module in
GitHub.  I need some text from the ITU legal department before I can put
the yang there.

**Pull request merged**
