### PR TITLE
Add in IOS-XR 5.3.3 native yang modules

### PR DESCRIPTION
**Pull request by einarnn**
Add in the native models for IOS-XR 5.3.3 and fix a couple of minor bugs with some of the check scripts.

### CODE REVIEW

**Comment by tnadeau** [comment]
Einar,

	I’ll review as soon as the Travis completes.

	—Tom

**Comment by einarnn** [comment]
Ok-dokey. I was happy enough to do that myself once the travis run completes, but feel free! :-)

Cheers,

Einar

**Comment by tnadeau** [comment]
We probably shouldn’t be committing our own pull requests when possible. Just sayin. *)

	—tom

**Comment by einarnn** [comment]
Sure. Over to you, then! ;-)

**Comment by tnadeau** [comment]
builds pass. looks good.

**Pull request merged**
