### PR TITLE
.1Qcr D2.2 updates

### PR DESCRIPTION
**Pull request by samans**
Updates to the draft files for IEEE P802.1Qcr.  Also includes fix to check.sh script.

### CODE REVIEW

**Comment by samans** [comment]
Yes.  Fixing the check.in script is one of the reasons for this commit.  When I run the script, everything compiles cleanly in my fork.

**Comment by tnadeau** [comment]
> Yes. Fixing the check.in script is one of the reasons for this commit. When I run the script, everything compiles cleanly in my fork.

Can you please re-run your tests to confirm nothing broke after I just merged Paul's big PR?

**Comment by tnadeau** [comment]
That is, you should resynch with the main branch and re-run the CI tests, please.

**Comment by samans** [comment]
Tom,

Something is wrong.  There should have been check.sh file updates along with updates to files in the Qcr directory.  It works on my system, so I'll have to rebase, apply the changes and try the pull request again.  I don't understand why it didn't work.  The messages I saw looked like the files were committed.  I'll try again.

**Pull request merged**
