### PR TITLE
Cronjob - every day pull and update of ietf draft yang files.

### PR DESCRIPTION
**Pull request by yang-catalog**
ietf extracted yang modules

### CODE REVIEW

**Comment by yang-catalog** [comment]
Hello @tnadeau  and @einarnn ,

Since review is required and I can not give review to my own patch I am not able to automatically merge this. Do you guys have any idea how could I proceed on this issue?

Miroslav Kovac

**Comment by tnadeau** [comment]
While reviews are necessary, I think you can review your own patch in this case.  I don’t
think the system has been setup to prohibit committers pushing on their own; its just our
policy for regular PRs.  

	—Tom

**Comment by einarnn** [comment]
Miroslav is experimenting, but it seems that GitHub doesn't allow the PR originator to review or merge their own PRs with the settings we have. Miroslav did a couple of tests via the GitHub API that seemed to indicate this. We'll experimenting with a possible alternative that leaves the current repo settings in place, but allows an automated workflow.

**Comment by einarnn** [comment]
Ok, I confirmed using the sandbox. Write now, a PR **must** be reviewed & approved & merged by someone who has merge privileges and who is not the same user. This also applies to administrators right now. We can relax this slightly, and allow admins to commit their own stuff, but "yang-catalog" isn't an admin, and so even if we relaxed that it couldn't commit its own PRs.

There are two solutions:

1. Make yang-catalog and admin user combined with releasing the constraint on admins.
2. Generate a token from a current admin user and let the automation software from YANG Catalog use that token to approve PRs.

I prefer the second approach, and that's what I've suggested Miroslav prototype. I've generated a token with restricted privileges from my account to try this.

**Pull request merged**
