### PR TITLE
Add remaining 802.1 Extension TLVs and changes from d1.0 WG ballot re…

### PR DESCRIPTION
**Pull request by PaulCongdon**
Added remaining 802.1 LLDP Extension TLV YANG modules and changes from d1.0 WG ballot comment resolution.  Verified check.sh script runs after rebasing with master

### CODE REVIEW

**Comment by PaulCongdon** [comment]
Thanks Elinar, I just realized, however, that I left out some bad prefix
names.

**Comment by einarnn** [comment]
Do you want this commit backed out?

Cheers,

Einar

**Comment by PaulCongdon** [comment]
No, sorry for the confusion.  I had a few more small changes after you
merged my last PR.  So, please just merge this one as well.

**Comment by einarnn** [comment]
Ok, second PR merged.

Cheers,

Einar

**Pull request merged**
