### PR TITLE
Add yang files

### PR DESCRIPTION
**Pull request by hwRouterYangAdmin**

### CODE REVIEW

**Comment by hwRouterYangAdmin** [comment]
i have commit a pull request with repo of huawei, with link https://github.com/Huawei/YangModels-yang 
but failed with "permmion denyed". And i could not handle with it.

**Comment by hwRouterYangAdmin** [comment]
could i add huawei yang files us like juniper ,make a link in README file ?

**Comment by miroslavKovacPantheon** [comment]
The travis check failed because path to yang files in sh script is invalid. It could be done similarly as bbf .sh script is done.

**Comment by hwRouterYangAdmin** [comment]
as i see script have  been updated,should i commit another pull request?
https://github.com/Huawei/yang/tree/a05266486fb74562d4d4c11f75cb760e9b376bc6

**Comment by miroslavKovacPantheon** [comment]
you should update this PR as we did on hackathon

**Comment by tnadeau** [comment]
Yes. Please commit everything as part of the same pull request. That is why
I withdrew the other one. 

	—Tom

**Comment by tnadeau** [comment]
You still need to push the file ./vendor/huawei/check-models.sh
The CI is failing because you call it, but it does not exist:

The command "./standard/ieee/check.sh" exited with 0.
0.19s$ ./vendor/huawei/check-models.sh
error ./network-router/8.9.10/huawei/*.yang: [Errno 2] No such file or directory: './network-router/8.9.10/huawei/*.yang'
The command "./vendor/huawei/check-models.sh" exited with 1.
Done. Your build exited with 1.

**Pull request closed without merging**
