### PR TITLE
Create iana-routing-types.yang symlink

### PR DESCRIPTION
**Pull request by pbianchi**
The latest version of iana-routing-types.yang was added and a symlink
pointing to it was created.

### CODE REVIEW

**Comment by pbianchi** [comment]
Also, I would suggest maintaining a symbolik link for each yang even for the ones that have only one revision on the repository. If you think this is a good idea I can also create another pull request with it.

**Comment by einarnn** [comment]
Maintaining links in this way seems sensible. Would like feedback from @tnadeau, @bclaise and @xorrkaz also.

**Comment by bclaise** [comment]
Historically, I had symbolic links only when there were multiple revisions. 
-rw-rw-r-- 1 bclaise bclaise  34730 Dez  7 04:00 iana-if-type@2014-05-08.yang
-rw-rw-r-- 1 bclaise bclaise  37062 Dez  7 04:00 iana-if-type@2017-01-19.yang
lrwxrwxrwx 1 bclaise bclaise     28 Dez  7 04:00 iana-if-type.yang -> iana-if-type@2017-01-19.yang
-rw-rw-r-- 1 bclaise bclaise  15931 Dez  7 04:00 ietf-inet-types@2010-09-24.yang
-rw-rw-r-- 1 bclaise bclaise  16830 Dez  7 04:00 ietf-inet-types@2013-07-15.yang
lrwxrwxrwx 1 bclaise bclaise     31 Dez  7 04:00 ietf-inet-types.yang -> ietf-inet-types@2013-07-15.yang

I don't believe there are any drawbacks to have sym. links by default, even if not necessary.

**Comment by miroslavKovacPantheon** [comment]
those symlinks are still in there. We use those to point to the latest revision. But I don t see any problem neither on having symlinks for each module.

**Pull request merged**
