### PR TITLE
Updated the RFC-extracted YANG data models

### PR DESCRIPTION
**Pull request by bclaise**

### CODE REVIEW

**Comment by tnadeau** [comment]
check.sh passes:

[server:yang/standard/ietf] tnadeau% ./check.sh 
Checking modules with pyang command:

    pyang --verbose MODULE

Checking yang files in RFC

pyang --verbose iana-crypt-hash@2014-08-06.yang
pyang --verbose iana-if-type.yang
pyang --verbose ietf-complex-types@2011-03-15.yang
pyang --verbose ietf-inet-types@2010-09-24.yang
pyang --verbose ietf-inet-types@2013-07-15.yang
pyang --verbose ietf-interfaces@2014-05-08.yang
pyang --verbose ietf-ip@2014-06-16.yang
pyang --verbose ietf-ipfix-psamp@2012-09-05.yang
pyang --verbose ietf-netconf-acm@2012-02-22.yang
pyang --verbose ietf-netconf-monitoring@2010-10-04.yang
pyang --verbose ietf-netconf-notifications.yang
pyang --verbose ietf-netconf-partial-lock.yang
pyang --verbose ietf-netconf-time@2016-01-26.yang
pyang --verbose ietf-netconf-with-defaults.yang
pyang --verbose ietf-netconf@2011-06-01.yang
pyang --verbose ietf-snmp-common.yang
pyang --verbose ietf-snmp-community.yang
pyang --verbose ietf-snmp-engine.yang
pyang --verbose ietf-snmp-notification.yang
pyang --verbose ietf-snmp-proxy.yang
pyang --verbose ietf-snmp-ssh.yang
pyang --verbose ietf-snmp-target.yang
pyang --verbose ietf-snmp-tls.yang
pyang --verbose ietf-snmp-tsm.yang
pyang --verbose ietf-snmp-usm.yang
pyang --verbose ietf-snmp-vacm.yang
pyang --verbose ietf-snmp.yang
pyang --verbose ietf-system@2014-08-06.yang
pyang --verbose ietf-template@2010-05-18.yang
pyang --verbose ietf-x509-cert-to-name.yang
pyang --verbose ietf-yang-smiv2@2012-06-22.yang
pyang --verbose ietf-yang-types@2010-09-24.yang
pyang --verbose ietf-yang-types@2013-07-15.yang
[server:yang/standard/ietf] tnadeau%

**Comment by bclaise** [comment]
I was afraid that the compilation would fail. Indeed, pyang works, but not with the --ietf option
See claise.be:

        YANG data models extracted from IETF RFCs: not all pass compilation correctly [http://www.claise.be/RFCStandardYANGPageCompilation.html] . It looks like we learned during the YANG data model publication process :-)

Regards, B

**Comment by einarnn** [comment]
Currently the travis.ci check script for IETF models doesn't enable the --ietf flag because of the vast number of non-compliances. So, you get a partial check that basic compilation is ok. You can see the tests run here:

https://github.com/YangModels/yang/blob/master/standard/ietf/check.sh

BTW, you can enable travis on your own fork and check before you do a pull request.

Cheers,

Einar

**Comment by tnadeau** [comment]
So you are observing the problem I raised over a year ago when I asked about how to fix compilation using —ietf flag.  
At the time, you and others told me that it was not a problem and that we should ignore it.  Should we try to fix this now?

	—Tom

**Comment by bclaise** [comment]
I try to impose --ietf for all IETF drafts. The issue is that some YANG data model in RFC don't pass --ietf.

**Comment by tnadeau** [comment]
So in the Yang repo right now, we can make exceptions in the CI (its just a shell script that runs pyang for each module). Its easy enough to add an “exceptions” section.

	Probably a better, more seamless solution, is to add some sort of exception file you can feed to pyang that instructs it to relax the constraints for specific modules.

	—Tom

**Pull request merged**
