### PR TITLE
Cron job - every day pull and update of ietf draft yang files.

### PR DESCRIPTION
**Pull request by yang-catalog**
ietf extracted yang modules

### CODE REVIEW

**Comment by einarnn** [comment]
Closing because I’d like to see a new Commit with typos in Commit messages addressed.

**Comment by tnadeau** [comment]
I’d also like to understand why we are getting frequent PRs for “every day pull/update cron job”.
Why are PRs being created for this?  If all you want to do is pull the latest files down, you don’t
need to do a PR for that.

	—Tom

**Comment by tnadeau** [comment]
Are we sure we want to do this in an automated manner?  I see lots of danger lurking here.

	—Tom

**Comment by miroslavKovacPantheon** [comment]
I was asked to do that cause almost every day there are some new files to be added or updated. Maybe Einar could anwer this. @einarnn

**Comment by einarnn** [comment]
I think that if we have run the process in a sandbox, with the same checks that we use for standard checkins enabled, and we are not overwriting what I'll call "specifically maintained content" (e.g. vendor maintained content), then it should be fine.

We have ensured that the "yang-catalog" user makes use of the appropriate Travis.CI webhooks at two points. First, when it checks in content to its fork, second when it submits a PR to the main repo. If either CI build fails, the process is aborted. This means we also get to catch any potential merge conflicts that cause breakage.

The one thing, @miroslavKovacPantheon, is do we check that the as far as GitHub is concerned the PR can be automatically merged? I can't recall if we discussed that?

@tnadeau, would you be happier if we did something like keep the tooling running for a slightly extended period on its own fork, maybe with a weekly manual PR that is reviewed? Then, once we have built up confidence after our débacle a couple of weeks ago, we can look at re-enabling the user for "auto-accepting" PRs that pass CI build checks.

Cheers,

Einar

**Comment by tnadeau** [comment]
> On Oct 11, 2017, at 10:31 AM, Einar Nilsen-Nygaard <notifications@github.com> wrote:
> 
> I think that if we have run the process in a sandbox, with the same checks that we use for standard checkins enabled, and we are not overwriting what I'll call "specifically maintained content" (e.g. vendor maintained content), then it should be fine.
> 
> 
	But if the content is not maintained, why are we checking it in?  If the files are truly ephemeral, they should be generated on the fly.
One of the benefits of the repo is its stability.  As we saw the other week, there are LOTS of consumers of this and they clearly 
rely on the repo’s stability.  The last thing I want to do is have half the files in the repo being updated daily, and worse, having something
that is in that automatic process blow the whole thing up, and worse, do so in a way that no one notices for a while. Unwinding this
sort of trainwreck will not be fun.
> We have ensured that the "yang-catalog" user makes use of the appropriate Travis.CI webhooks at two points. First, when it checks in content to its fork, second when it submits a PR to the main repo. If either CI build fails, the process is aborted. This means we also get to catch any potential merge conflicts that cause breakage.
> 
> The one thing, @miroslavKovacPantheon <https://github.com/miroslavkovacpantheon>, is do we check that the as far as GitHub is concerned the PR can be automatically merged? I can't recall if we discussed that?
> 
> 
	After the last disaster, I am very much not in favor of any automatic merging.  Commit authorization is limited on purpose.
> @tnadeau <https://github.com/tnadeau>, would you be happier if we did something like keep the tooling running for a slightly extended period on its own fork, maybe with a weekly manual PR that is reviewed? Then, once we have built up confidence after our débacle a couple of weeks ago, we can look at re-enabling the user for "auto-accepting" PRs that pass CI build checks.
> 
> 	

	Do we really have such a large number of modules that need updating on such a frequent basis, that we need to automate this?
I still don’t groc why doing this manually is so bad.

	—Tom

**Comment by miroslavKovacPantheon** [comment]
@einarnn if there would be a problem github will not let it merge will it? next day there would be a new PR...

**Comment by bclaise** [comment]
Tom, the point is that we don't have a location for those IETF draft extracted YANG modules.
The yangcatalog.org is not a YANG module repository. Therefore the idea is push the latest YANG module revisions on regular basis.
Note: I wish the IETF would work from github, but we're not there yet.

**Comment by tnadeau** [comment]
Maybe the solution is to create a “scratch” area and only allow that to be auto-merged but preserve
the rest of the area as it currently is used.

	—Tom

**Comment by bclaise** [comment]
that would work. That's possible in github?

**Comment by tnadeau** [comment]
Yes, we just create another branch in the directory structure and designate it as such etc…

	We could allow auto-merge from the yangcatalog UID but we’d have to make it a committer.
I’d need assurances from you guys that this user was under strict control and scrutiny so we avoid
what happened a few years ago.  Specifically, that it never writes to any dirs other than the
designated subdir area.  If we can do that, I think we have a solution.

	—Tom

**Comment by miroslavKovacPantheon** [comment]
@tnadeau I would be ok with that. Right now it is set that it only writes to experimental/ietf-extracted-YANG-modules and standard/ietf/RFC but we can make it to write somewhere else. Also if you want I can point you to a specific code that works with travis and creates a PR and makes merge to review.. I can walk you through it if needed.

   Miroslav

**Comment by tnadeau** [comment]
I’ve reviewed that code early on, but it might be a good idea to sit down with Einar and myself at a minimum, to go over this. I have time for this today, but Friday won’t work. I am in EST.

**Comment by miroslavKovacPantheon** [comment]
I could do it today too in like next two hours if @einarnn have time too

**Comment by tnadeau** [comment]
Unfortunately I am booked now from 1-2PM EST, so we have to wrap up by then. Einar are you available?
.

**Comment by einarnn** [comment]
Guys,

Sorry, I was unavailable pretty much from when this las message arrived.

Cheers,

Einar

**Comment by tnadeau** [comment]
When on Monday or Tuesday next week works? I am not available today (Fri).

**Comment by miroslavKovacPantheon** [comment]
I am availible both days from 9:00 AM CEST to 04:00 PM CEST

**Comment by einarnn** [comment]
I can do a short meeting either day probably. Technically on vacation next week, so I’d rather wait until week of 23rd October if possible?

Cheers,

Einar

**Comment by miroslavKovacPantheon** [comment]
I am ok both ways..

**Comment by tnadeau** [comment]
Cool. How about Tuesday at 9AM EST/3PM CEST?

	—Tom

**Comment by miroslavKovacPantheon** [comment]
OK for me. Will you schedule a webex meeting or something else?

**Comment by tnadeau** [comment]
We can use my Zoom: 

Tom Nadeau is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/846444537 <https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F846444537&sa=D&usd=2&usg=AFQjCNFUCZlr09vl5a0KJBJYE9CA3OriaQ>

Or iPhone one-tap :
    US: +16699006833,,846444537#  or +16468769923,,846444537# 
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 646 876 9923 
    Meeting ID: 846 444 537
    International numbers available: https://zoom.us/zoomconference?m=4_5lvk3rXfOjjukQmK0EVSWHpKACTSLh <https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fzoomconference%3Fm%3D4_5lvk3rXfOjjukQmK0EVSWHpKACTSLh&sa=D&usd=2&usg=AFQjCNHw6rqt_SWmiYtX_9esD2-raBKocQ>

**Comment by einarnn** [comment]
Ok. I’ll try to make it!

**Comment by tnadeau** [comment]
Did we settle on a date/time?

	—Tom

**Comment by miroslavKovacPantheon** [comment]
yeah I think so.. tomorow (tuesday) at 9AM EST/3PM CEST.. @bclaise  will join as well

**Comment by tnadeau** [comment]
Tom Nadeau is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/488573379 <https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F488573379&sa=D&usd=2&usg=AFQjCNHw8CHzOsm5X32Fj0XmEhYLXbX2Og>

Or iPhone one-tap :
    US: +16699006833,,488573379#  or +16468769923,,488573379# 
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 646 876 9923 
    Meeting ID: 488 573 379
    International numbers available: https://zoom.us/zoomconference?m=YOU0t11sK_og6rwFnD26cJ2_0FUeopNH <https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fzoomconference%3Fm%3DYOU0t11sK_og6rwFnD26cJ2_0FUeopNH&sa=D&usd=2&usg=AFQjCNF9SBNV4qwbc_lsLWnzGFQQ-r6KHw>

**Pull request closed without merging**
