### PR TITLE
Initial version of the BFD and TWAMP YANG model.

### PR DESCRIPTION
**Pull request by mjethanandani**
And here is the tree diagram for the model.

module: ietf-bfd
augment /rt:routing/rt:routing-instance/rt:routing-protocols/rt:routing-protocol:
   +--rw bfd
      +--rw bfd-cfg
      |  +--rw bfd-session-cfg
      |  |  +--rw session-ip-mh* [source-addr dest-addr]
      |  |     +--rw source-addr                 inet:ip-address
      |  |     +--rw dest-addr                   inet:ip-address
      |  |     +--rw admin-down?                 boolean
      |  |     +--rw local-multiplier?           multiplier
      |  |     +--rw (interval-config-type)?
      |  |     |  +--:(tx-rx-intervals)
      |  |     |  |  +--rw desired-min-tx-interval     uint32
      |  |     |  |  +--rw required-min-rx-interval    uint32
      |  |     |  +--:(single-interval)
      |  |     |     +--rw min-interval                uint32
      |  |     +--rw demand-enabled?             boolean
      |  |     +--rw enable-authentication?      boolean
      |  |     +--rw authentication-parms {bfd-authentication}?
      |  |     |  +--rw key-chain-name?   string
      |  |     |  +--rw algorithm?        bfd-auth-algorithm
      |  |     +--rw tx-ttl?                     ttl
      |  |     +--rw rx-ttl                      ttl
      |  +--rw bfd-interface-cfg* [interface] {bfd-interface-config}?
      |     +--rw interface                        if:interface-ref
      |     +--rw local-multiplier?                multiplier
      |     +--rw (interval-config-type)?
      |     |  +--:(tx-rx-intervals)
      |     |  |  +--rw desired-min-tx-interval          uint32
      |     |  |  +--rw required-min-rx-interval         uint32
      |     |  +--:(single-interval)
      |     |     +--rw min-interval                     uint32
      |     +--rw demand-enabled?                  boolean
      |     +--rw enable-authentication?           boolean
      |     +--rw authentication-parms {bfd-authentication}?
      |     |  +--rw key-chain-name?   string
      |     |  +--rw algorithm?        bfd-auth-algorithm
      |     +--rw desired-min-echo-tx-interval?    uint32
      |     +--rw required-min-echo-rx-interval?   uint32
      +--ro bfd-oper
         +--ro bfd-session-statistics
         |  +--ro ip-sh-session-num?     uint32
         |  +--ro ip-mh-session-num?     uint32
         |  +--ro total-session-num?     uint32
         |  +--ro session-up-num?        uint32
         |  +--ro sess-down-num?         uint32
         |  +--ro sess-admin-down-num?   uint32
         +--ro bfd-session-lists
            +--ro session-ip-sh* [interface dest-addr]
            |  +--ro interface               if:interface-ref
            |  +--ro dest-addr               inet:ip-address
            |  +--ro source-addr?            inet:ip-address
            |  +--ro session-type?           bfd-session-type
            |  +--ro local-discriminator?    discriminator
            |  +--ro remote-discriminator?   discriminator
            |  +--ro remote-multiplier?      multiplier
            |  +--ro out-interface?          if:interface-ref
            |  +--ro demand-capability?      boolean
            |  +--ro source-port?            inet:port-number
            |  +--ro dest-port?              inet:port-number
            |  +--ro session-running*
            |  |  +--ro session-index?                 uint32
            |  |  +--ro local-state?                   state
            |  |  +--ro remote-state?                  state
            |  |  +--ro local-diagnostic?              diagnostic
            |  |  +--ro remote-diagnostic?             diagnostic
            |  |  +--ro detection-mode?                enumeration
            |  |  +--ro negotiated-tx-interval?        uint32
            |  |  +--ro negotiated-rx-interval?        uint32
            |  |  +--ro negotiated-echo-tx-interval?   uint32
            |  |  +--ro detection-time?                uint32
            |  +--ro sesssion-statistics*
            |     +--ro create-time?            yang:date-and-time
            |     +--ro last-down-time?         yang:date-and-time
            |     +--ro last-up-time?           yang:date-and-time
            |     +--ro down-count?             uint32
            |     +--ro admin-down-count?       uint32
            |     +--ro receive-packet-count?   uint64
            |     +--ro send-packet-count?      uint64
            |     +--ro receive-bad-packet?     uint64
            |     +--ro send-failed-packet?     uint64
            +--ro session-ip-mh-group* [source-addr dest-addr]
            |  +--ro source-addr      inet:ip-address
            |  +--ro dest-addr        inet:ip-address
            |  +--ro session-ip-mh* [source-port]
            |     +--ro ttl?                    ttl
            |     +--ro session-type?           bfd-session-type
            |     +--ro local-discriminator?    discriminator
            |     +--ro remote-discriminator?   discriminator
            |     +--ro remote-multiplier?      multiplier
            |     +--ro out-interface?          if:interface-ref
            |     +--ro demand-capability?      boolean
            |     +--ro source-port             inet:port-number
            |     +--ro dest-port?              inet:port-number
            |     +--ro session-running*
            |     |  +--ro session-index?                 uint32
            |     |  +--ro local-state?                   state
            |     |  +--ro remote-state?                  state
            |     |  +--ro local-diagnostic?              diagnostic
            |     |  +--ro remote-diagnostic?             diagnostic
            |     |  +--ro detection-mode?                enumeration
            |     |  +--ro negotiated-tx-interval?        uint32
            |     |  +--ro negotiated-rx-interval?        uint32
            |     |  +--ro negotiated-echo-tx-interval?   uint32
            |     |  +--ro detection-time?                uint32
            |     +--ro sesssion-statistics*
            |        +--ro create-time?            yang:date-and-time
            |        +--ro last-down-time?         yang:date-and-time
            |        +--ro last-up-time?           yang:date-and-time
            |        +--ro down-count?             uint32
            |        +--ro admin-down-count?       uint32
            |        +--ro receive-packet-count?   uint64
            |        +--ro send-packet-count?      uint64
            |        +--ro receive-bad-packet?     uint64
            |        +--ro send-failed-packet?     uint64
            +--ro session-te-tunnel* [tunnel-name]
            |  +--ro tunnel-name             string
            |  +--ro session-type?           bfd-session-type
            |  +--ro local-discriminator?    discriminator
            |  +--ro remote-discriminator?   discriminator
            |  +--ro remote-multiplier?      multiplier
            |  +--ro out-interface?          if:interface-ref
            |  +--ro demand-capability?      boolean
            |  +--ro source-port?            inet:port-number
            |  +--ro dest-port?              inet:port-number
            |  +--ro session-running*
            |  |  +--ro session-index?                 uint32
            |  |  +--ro local-state?                   state
            |  |  +--ro remote-state?                  state
            |  |  +--ro local-diagnostic?              diagnostic
            |  |  +--ro remote-diagnostic?             diagnostic
            |  |  +--ro detection-mode?                enumeration
            |  |  +--ro negotiated-tx-interval?        uint32
            |  |  +--ro negotiated-rx-interval?        uint32
            |  |  +--ro negotiated-echo-tx-interval?   uint32
            |  |  +--ro detection-time?                uint32
            |  +--ro sesssion-statistics*
            |     +--ro create-time?            yang:date-and-time
            |     +--ro last-down-time?         yang:date-and-time
            |     +--ro last-up-time?           yang:date-and-time
            |     +--ro down-count?             uint32
            |     +--ro admin-down-count?       uint32
            |     +--ro receive-packet-count?   uint64
            |     +--ro send-packet-count?      uint64
            |     +--ro receive-bad-packet?     uint64
            |     +--ro send-failed-packet?     uint64
            +--ro session-ldp-lsp-group* [ldp-fec]
            |  +--ro ldp-fec            inet:ip-prefix
            |  +--ro session-ldp-lsp* [source-port]
            |     +--ro ttl?                    ttl
            |     +--ro session-type?           bfd-session-type
            |     +--ro local-discriminator?    discriminator
            |     +--ro remote-discriminator?   discriminator
            |     +--ro remote-multiplier?      multiplier
            |     +--ro out-interface?          if:interface-ref
            |     +--ro demand-capability?      boolean
            |     +--ro source-port             inet:port-number
            |     +--ro dest-port?              inet:port-number
            |     +--ro session-running*
            |     |  +--ro session-index?                 uint32
            |     |  +--ro local-state?                   state
            |     |  +--ro remote-state?                  state
            |     |  +--ro local-diagnostic?              diagnostic
            |     |  +--ro remote-diagnostic?             diagnostic
            |     |  +--ro detection-mode?                enumeration
            |     |  +--ro negotiated-tx-interval?        uint32
            |     |  +--ro negotiated-rx-interval?        uint32
            |     |  +--ro negotiated-echo-tx-interval?   uint32
            |     |  +--ro detection-time?                uint32
            |     +--ro sesssion-statistics*
            |        +--ro create-time?            yang:date-and-time
            |        +--ro last-down-time?         yang:date-and-time
            |        +--ro last-up-time?           yang:date-and-time
            |        +--ro down-count?             uint32
            |        +--ro admin-down-count?       uint32
            |        +--ro receive-packet-count?   uint64
            |        +--ro send-packet-count?      uint64
            |        +--ro receive-bad-packet?     uint64
            |        +--ro send-failed-packet?     uint64
            +--ro session-lag* [lag-name]
               +--ro lag-name             if:interface-ref
               +--ro session-lag-micro* [member-link]
                  +--ro member-link             if:interface-ref
                  +--ro session-type?           bfd-session-type
                  +--ro local-discriminator?    discriminator
                  +--ro remote-discriminator?   discriminator
                  +--ro remote-multiplier?      multiplier
                  +--ro out-interface?          if:interface-ref
                  +--ro demand-capability?      boolean
                  +--ro source-port?            inet:port-number
                  +--ro dest-port?              inet:port-number
                  +--ro session-running*
                  |  +--ro session-index?                 uint32
                  |  +--ro local-state?                   state
                  |  +--ro remote-state?                  state
                  |  +--ro local-diagnostic?              diagnostic
                  |  +--ro remote-diagnostic?             diagnostic
                  |  +--ro detection-mode?                enumeration
                  |  +--ro negotiated-tx-interval?        uint32
                  |  +--ro negotiated-rx-interval?        uint32
                  |  +--ro negotiated-echo-tx-interval?   uint32
                  |  +--ro detection-time?                uint32
                  +--ro sesssion-statistics*
                     +--ro create-time?            yang:date-and-time
                     +--ro last-down-time?         yang:date-and-time
                     +--ro last-up-time?           yang:date-and-time
                     +--ro down-count?             uint32
                     +--ro admin-down-count?       uint32
                     +--ro receive-packet-count?   uint64
                     +--ro send-packet-count?      uint64
                     +--ro receive-bad-packet?     uint64
                     +--ro send-failed-packet?     uint64
notifications:
   +---n bfd-singlehop-notification
   |  +--ro local-discr?              discriminator
   |  +--ro remote-discr?             discriminator
   |  +--ro new-state?                state
   |  +--ro state-change-reason?      string
   |  +--ro time-in-previous-state?   string
   |  +--ro dest-addr?                inet:ip-address
   |  +--ro source-addr?              inet:ip-address
   |  +--ro session-index?            uint32
   |  +--ro session-type?             bfd-session-type
   |  +--ro interface?                if:interface-ref
   |  +--ro echo-enabled?             boolean
   +---n bfd-multihop-notification
   |  +--ro local-discr?              discriminator
   |  +--ro remote-discr?             discriminator
   |  +--ro new-state?                state
   |  +--ro state-change-reason?      string
   |  +--ro time-in-previous-state?   string
   |  +--ro dest-addr?                inet:ip-address
   |  +--ro source-addr?              inet:ip-address
   |  +--ro session-index?            uint32
   |  +--ro session-type?             bfd-session-type
   +---n bfd-te-tunnel-notification
   |  +--ro local-discr?              discriminator
   |  +--ro remote-discr?             discriminator
   |  +--ro new-state?                state
   |  +--ro state-change-reason?      string
   |  +--ro time-in-previous-state?   string
   |  +--ro dest-addr?                inet:ip-address
   |  +--ro source-addr?              inet:ip-address
   |  +--ro session-index?            uint32
   |  +--ro session-type?             bfd-session-type
   |  +--ro tunnel-name?              string
   +---n bfd-ldp-lsp-notification
   |  +--ro local-discr?              discriminator
   |  +--ro remote-discr?             discriminator
   |  +--ro new-state?                state
   |  +--ro state-change-reason?      string
   |  +--ro time-in-previous-state?   string
   |  +--ro dest-addr?                inet:ip-address
   |  +--ro source-addr?              inet:ip-address
   |  +--ro session-index?            uint32
   |  +--ro session-type?             bfd-session-type
   |  +--ro ldp-fec?                  inet:ip-prefix
   |  +--ro source-port?              inet:port-number
   +---n bfd-lag-notification
      +--ro local-discr?              discriminator
      +--ro remote-discr?             discriminator
      +--ro new-state?                state
      +--ro state-change-reason?      string
      +--ro time-in-previous-state?   string
      +--ro dest-addr?                inet:ip-address
      +--ro source-addr?              inet:ip-address
      +--ro session-index?            uint32
      +--ro session-type?             bfd-session-type
      +--ro lag-name?                 if:interface-ref
      +--ro member-link?              if:interface-ref

### CODE REVIEW

**Comment by mjethanandani** [comment]
Fixed a few --ietf errors.

**Comment by tnadeau** [comment]
can you please paste the output from pyang?

**Comment by mjethanandani** [comment]
Here is the output of pyang for twamp:

sjc-ads-5059:/ws/mahesh-sjc/git/yang/standard/ietf/DRAFT *969 > pyang --ietf -f tree -p .:../802.1x:../../../standard/ietf/RFC ietf-twamp.yang
module: ietf-twamp
   +--rw twamp
      +--rw twamp-client! {control-client}?
      |  +--rw client-admin-state              boolean
      |  +--rw mode-preference-chain* [priority]
      |  |  +--rw priority    uint16
      |  |  +--rw mode?       mode
      |  +--rw key-chain* [key-id]
      |  |  +--rw key-id        string
      |  |  +--rw secret-key?   string
      |  +--rw twamp-client-ctrl-connection* [ctrl-connection-name]
      |     +--rw ctrl-connection-name     string
      |     +--rw client-ip?               inet:ip-address
      |     +--rw server-ip                inet:ip-address
      |     +--rw server-tcp-port?         inet:port-number
      |     +--rw dscp?                    inet:dscp
      |     +--rw key-id?                  string
      |     +--rw max-count?               uint32
      |     +--ro client-tcp-port?         inet:port-number
      |     +--ro server-start-time?       uint64
      |     +--ro ctrl-connection-state?   ctrl-connection-state
      |     +--ro selected-mode?           mode
      |     +--ro token?                   binary
      |     +--ro client-iv?               binary
      |     +--rw twamp-session-request* [test-session-name]
      |        +--rw test-session-name     string
      |        +--rw sender-ip?            inet:ip-address
      |        +--rw sender-udp-port?      inet:port-number
      |        +--rw reflector-ip          inet:ip-address
      |        +--rw reflector-udp-port?   inet:port-number
      |        +--rw timeout?              uint64
      |        +--rw padding-length?       uint32
      |        +--rw dscp?                 inet:dscp
      |        +--rw start-time?           uint64
      |        +--rw repeat?               boolean
      |        +--rw repeat-interval?      uint32
      |        +--rw pm-reg-list* [pm-index]
      |        |  +--rw pm-index    uint16
      |        +--ro test-session-state?   test-session-state
      |        +--ro sid?                  string
      +--rw twamp-server! {server}?
      |  +--rw server-admin-state              boolean
      |  +--rw server-tcp-port?                inet:port-number
      |  +--rw servwait?                       uint32
      |  +--rw dscp?                           inet:dscp
      |  +--rw count?                          uint32
      |  +--rw max-count?                      uint32
      |  +--rw modes?                          mode
      |  +--rw key-chain* [key-id]
      |  |  +--rw key-id        string
      |  |  +--rw secret-key?   string
      |  +--ro twamp-server-ctrl-connection* [client-ip client-tcp-port server-ip server-tcp-port]
      |     +--ro client-ip                       inet:ip-address
      |     +--ro client-tcp-port                 inet:port-number
      |     +--ro server-ip                       inet:ip-address
      |     +--ro server-tcp-port                 inet:port-number
      |     +--ro server-ctrl-connection-state?   server-ctrl-connection-state
      |     +--ro dscp?                           inet:dscp
      |     +--ro selected-mode?                  mode
      |     +--ro key-id?                         string
      |     +--ro count?                          uint32
      |     +--ro max-count?                      uint32
      |     +--ro salt?                           binary
      |     +--ro server-iv?                      binary
      |     +--ro challenge?                      binary
      +--rw twamp-session-sender {session-sender}?
      |  +--rw twamp-sender-test-session* [test-session-name]
      |     +--rw test-session-name          string
      |     +--ro ctrl-connection-name?      string
      |     +--rw fill-mode?                 fill-mode
      |     +--rw number-of-packets?         uint32
      |     +--rw (packet-distribution)?
      |     |  +--:(periodic)
      |     |  |  +--rw periodic-interval?         uint32
      |     |  |  +--rw periodic-interval-units?   units
      |     |  +--:(poisson)
      |     |     +--rw lambda?                    uint32
      |     |     +--rw lambda-units?              uint32
      |     |     +--rw max-interval?              uint32
      |     |     +--rw truncation-point-units?    units
      |     +--ro sender-session-state?      sender-session-state
      |     +--ro sent-packets?              uint32
      |     +--ro rcv-packets?               uint32
      |     +--ro last-sent-seq?             uint32
      |     +--ro last-rcv-seq?              uint32
      +--rw twamp-session-reflector {session-reflector}?
         +--rw refwait?                        uint32
         +--ro twamp-reflector-test-session* [sender-ip sender-udp-port reflector-ip reflector-udp-port]
            +--ro sid?                                 string
            +--ro sender-ip                            inet:ip-address
            +--ro sender-udp-port                      inet:port-number
            +--ro reflector-ip                         inet:ip-address
            +--ro reflector-udp-port                   inet:port-number
            +--ro parent-connection-client-ip?         inet:ip-address
            +--ro parent-connection-client-tcp-port?   inet:port-number
            +--ro parent-connection-server-ip?         inet:ip-address
            +--ro parent-connection-server-tcp-port?   inet:port-number
            +--ro dscp?                                inet:dscp
            +--ro sent-packets?                        uint32
            +--ro rcv-packets?                         uint32
            +--ro last-sent-seq?                       uint32
            +--ro last-rcv-seq?                        uint32

**Comment by mjethanandani** [comment]
And this is for BFD:

 > pyang --ietf -f tree -p .:../802.1x:../../../standard/ietf/RFC ietf-bfd.yang
module: ietf-bfd
augment /rt:routing/rt:routing-instance/rt:routing-protocols/rt:routing-protocol:
   +--rw bfd
      +--rw bfd-cfg
      |  +--rw bfd-session-cfg
      |  |  +--rw session-ip-mh* [source-addr dest-addr]
      |  |     +--rw source-addr                 inet:ip-address
      |  |     +--rw dest-addr                   inet:ip-address
      |  |     +--rw admin-down?                 boolean
      |  |     +--rw local-multiplier?           multiplier
      |  |     +--rw (interval-config-type)?
      |  |     |  +--:(tx-rx-intervals)
      |  |     |  |  +--rw desired-min-tx-interval     uint32
      |  |     |  |  +--rw required-min-rx-interval    uint32
      |  |     |  +--:(single-interval)
      |  |     |     +--rw min-interval                uint32
      |  |     +--rw demand-enabled?             boolean
      |  |     +--rw enable-authentication?      boolean
      |  |     +--rw authentication-parms {bfd-authentication}?
      |  |     |  +--rw key-chain-name?   string
      |  |     |  +--rw algorithm?        bfd-auth-algorithm
      |  |     +--rw tx-ttl?                     ttl
      |  |     +--rw rx-ttl                      ttl
      |  +--rw bfd-interface-cfg* [interface] {bfd-interface-config}?
      |     +--rw interface                        if:interface-ref
      |     +--rw local-multiplier?                multiplier
      |     +--rw (interval-config-type)?
      |     |  +--:(tx-rx-intervals)
      |     |  |  +--rw desired-min-tx-interval          uint32
      |     |  |  +--rw required-min-rx-interval         uint32
      |     |  +--:(single-interval)
      |     |     +--rw min-interval                     uint32
      |     +--rw demand-enabled?                  boolean
      |     +--rw enable-authentication?           boolean
      |     +--rw authentication-parms {bfd-authentication}?
      |     |  +--rw key-chain-name?   string
      |     |  +--rw algorithm?        bfd-auth-algorithm
      |     +--rw desired-min-echo-tx-interval?    uint32
      |     +--rw required-min-echo-rx-interval?   uint32
      +--ro bfd-oper
         +--ro bfd-session-statistics
         |  +--ro ip-sh-session-num?     uint32
         |  +--ro ip-mh-session-num?     uint32
         |  +--ro total-session-num?     uint32
         |  +--ro session-up-num?        uint32
         |  +--ro sess-down-num?         uint32
         |  +--ro sess-admin-down-num?   uint32
         +--ro bfd-session-lists
            +--ro session-ip-sh* [interface dest-addr]
            |  +--ro interface               if:interface-ref
            |  +--ro dest-addr               inet:ip-address
            |  +--ro source-addr?            inet:ip-address
            |  +--ro session-type?           bfd-session-type
            |  +--ro local-discriminator?    discriminator
            |  +--ro remote-discriminator?   discriminator
            |  +--ro remote-multiplier?      multiplier
            |  +--ro out-interface?          if:interface-ref
            |  +--ro demand-capability?      boolean
            |  +--ro source-port?            inet:port-number
            |  +--ro dest-port?              inet:port-number
            |  +--ro session-running*
            |  |  +--ro session-index?                 uint32
            |  |  +--ro local-state?                   state
            |  |  +--ro remote-state?                  state
            |  |  +--ro local-diagnostic?              diagnostic
            |  |  +--ro remote-diagnostic?             diagnostic
            |  |  +--ro detection-mode?                enumeration
            |  |  +--ro negotiated-tx-interval?        uint32
            |  |  +--ro negotiated-rx-interval?        uint32
            |  |  +--ro negotiated-echo-tx-interval?   uint32
            |  |  +--ro detection-time?                uint32
            |  +--ro sesssion-statistics*
            |     +--ro create-time?            yang:date-and-time
            |     +--ro last-down-time?         yang:date-and-time
            |     +--ro last-up-time?           yang:date-and-time
            |     +--ro down-count?             uint32
            |     +--ro admin-down-count?       uint32
            |     +--ro receive-packet-count?   uint64
            |     +--ro send-packet-count?      uint64
            |     +--ro receive-bad-packet?     uint64
            |     +--ro send-failed-packet?     uint64
            +--ro session-ip-mh-group* [source-addr dest-addr]
            |  +--ro source-addr      inet:ip-address
            |  +--ro dest-addr        inet:ip-address
            |  +--ro session-ip-mh* [source-port]
            |     +--ro ttl?                    ttl
            |     +--ro session-type?           bfd-session-type
            |     +--ro local-discriminator?    discriminator
            |     +--ro remote-discriminator?   discriminator
            |     +--ro remote-multiplier?      multiplier
            |     +--ro out-interface?          if:interface-ref
            |     +--ro demand-capability?      boolean
            |     +--ro source-port             inet:port-number
            |     +--ro dest-port?              inet:port-number
            |     +--ro session-running*
            |     |  +--ro session-index?                 uint32
            |     |  +--ro local-state?                   state
            |     |  +--ro remote-state?                  state
            |     |  +--ro local-diagnostic?              diagnostic
            |     |  +--ro remote-diagnostic?             diagnostic
            |     |  +--ro detection-mode?                enumeration
            |     |  +--ro negotiated-tx-interval?        uint32
            |     |  +--ro negotiated-rx-interval?        uint32
            |     |  +--ro negotiated-echo-tx-interval?   uint32
            |     |  +--ro detection-time?                uint32
            |     +--ro sesssion-statistics*
            |        +--ro create-time?            yang:date-and-time
            |        +--ro last-down-time?         yang:date-and-time
            |        +--ro last-up-time?           yang:date-and-time
            |        +--ro down-count?             uint32
            |        +--ro admin-down-count?       uint32
            |        +--ro receive-packet-count?   uint64
            |        +--ro send-packet-count?      uint64
            |        +--ro receive-bad-packet?     uint64
            |        +--ro send-failed-packet?     uint64
            +--ro session-te-tunnel* [tunnel-name]
            |  +--ro tunnel-name             string
            |  +--ro session-type?           bfd-session-type
            |  +--ro local-discriminator?    discriminator
            |  +--ro remote-discriminator?   discriminator
            |  +--ro remote-multiplier?      multiplier
            |  +--ro out-interface?          if:interface-ref
            |  +--ro demand-capability?      boolean
            |  +--ro source-port?            inet:port-number
            |  +--ro dest-port?              inet:port-number
            |  +--ro session-running*
            |  |  +--ro session-index?                 uint32
            |  |  +--ro local-state?                   state
            |  |  +--ro remote-state?                  state
            |  |  +--ro local-diagnostic?              diagnostic
            |  |  +--ro remote-diagnostic?             diagnostic
            |  |  +--ro detection-mode?                enumeration
            |  |  +--ro negotiated-tx-interval?        uint32
            |  |  +--ro negotiated-rx-interval?        uint32
            |  |  +--ro negotiated-echo-tx-interval?   uint32
            |  |  +--ro detection-time?                uint32
            |  +--ro sesssion-statistics*
            |     +--ro create-time?            yang:date-and-time
            |     +--ro last-down-time?         yang:date-and-time
            |     +--ro last-up-time?           yang:date-and-time
            |     +--ro down-count?             uint32
            |     +--ro admin-down-count?       uint32
            |     +--ro receive-packet-count?   uint64
            |     +--ro send-packet-count?      uint64
            |     +--ro receive-bad-packet?     uint64
            |     +--ro send-failed-packet?     uint64
            +--ro session-ldp-lsp-group* [ldp-fec]
            |  +--ro ldp-fec            inet:ip-prefix
            |  +--ro session-ldp-lsp* [source-port]
            |     +--ro ttl?                    ttl
            |     +--ro session-type?           bfd-session-type
            |     +--ro local-discriminator?    discriminator
            |     +--ro remote-discriminator?   discriminator
            |     +--ro remote-multiplier?      multiplier
            |     +--ro out-interface?          if:interface-ref
            |     +--ro demand-capability?      boolean
            |     +--ro source-port             inet:port-number
            |     +--ro dest-port?              inet:port-number
            |     +--ro session-running*
            |     |  +--ro session-index?                 uint32
            |     |  +--ro local-state?                   state
            |     |  +--ro remote-state?                  state
            |     |  +--ro local-diagnostic?              diagnostic
            |     |  +--ro remote-diagnostic?             diagnostic
            |     |  +--ro detection-mode?                enumeration
            |     |  +--ro negotiated-tx-interval?        uint32
            |     |  +--ro negotiated-rx-interval?        uint32
            |     |  +--ro negotiated-echo-tx-interval?   uint32
            |     |  +--ro detection-time?                uint32
            |     +--ro sesssion-statistics*
            |        +--ro create-time?            yang:date-and-time
            |        +--ro last-down-time?         yang:date-and-time
            |        +--ro last-up-time?           yang:date-and-time
            |        +--ro down-count?             uint32
            |        +--ro admin-down-count?       uint32
            |        +--ro receive-packet-count?   uint64
            |        +--ro send-packet-count?      uint64
            |        +--ro receive-bad-packet?     uint64
            |        +--ro send-failed-packet?     uint64
            +--ro session-lag* [lag-name]
               +--ro lag-name             if:interface-ref
               +--ro session-lag-micro* [member-link]
                  +--ro member-link             if:interface-ref
                  +--ro session-type?           bfd-session-type
                  +--ro local-discriminator?    discriminator
                  +--ro remote-discriminator?   discriminator
                  +--ro remote-multiplier?      multiplier
                  +--ro out-interface?          if:interface-ref
                  +--ro demand-capability?      boolean
                  +--ro source-port?            inet:port-number
                  +--ro dest-port?              inet:port-number
                  +--ro session-running*
                  |  +--ro session-index?                 uint32
                  |  +--ro local-state?                   state
                  |  +--ro remote-state?                  state
                  |  +--ro local-diagnostic?              diagnostic
                  |  +--ro remote-diagnostic?             diagnostic
                  |  +--ro detection-mode?                enumeration
                  |  +--ro negotiated-tx-interval?        uint32
                  |  +--ro negotiated-rx-interval?        uint32
                  |  +--ro negotiated-echo-tx-interval?   uint32
                  |  +--ro detection-time?                uint32
                  +--ro sesssion-statistics*
                     +--ro create-time?            yang:date-and-time
                     +--ro last-down-time?         yang:date-and-time
                     +--ro last-up-time?           yang:date-and-time
                     +--ro down-count?             uint32
                     +--ro admin-down-count?       uint32
                     +--ro receive-packet-count?   uint64
                     +--ro send-packet-count?      uint64
                     +--ro receive-bad-packet?     uint64
                     +--ro send-failed-packet?     uint64
notifications:
   +---n bfd-singlehop-notification
   |  +--ro local-discr?              discriminator
   |  +--ro remote-discr?             discriminator
   |  +--ro new-state?                state
   |  +--ro state-change-reason?      string
   |  +--ro time-in-previous-state?   string
   |  +--ro dest-addr?                inet:ip-address
   |  +--ro source-addr?              inet:ip-address
   |  +--ro session-index?            uint32
   |  +--ro session-type?             bfd-session-type
   |  +--ro interface?                if:interface-ref
   |  +--ro echo-enabled?             boolean
   +---n bfd-multihop-notification
   |  +--ro local-discr?              discriminator
   |  +--ro remote-discr?             discriminator
   |  +--ro new-state?                state
   |  +--ro state-change-reason?      string
   |  +--ro time-in-previous-state?   string
   |  +--ro dest-addr?                inet:ip-address
   |  +--ro source-addr?              inet:ip-address
   |  +--ro session-index?            uint32
   |  +--ro session-type?             bfd-session-type
   +---n bfd-te-tunnel-notification
   |  +--ro local-discr?              discriminator
   |  +--ro remote-discr?             discriminator
   |  +--ro new-state?                state
   |  +--ro state-change-reason?      string
   |  +--ro time-in-previous-state?   string
   |  +--ro dest-addr?                inet:ip-address
   |  +--ro source-addr?              inet:ip-address
   |  +--ro session-index?            uint32
   |  +--ro session-type?             bfd-session-type
   |  +--ro tunnel-name?              string
   +---n bfd-ldp-lsp-notification
   |  +--ro local-discr?              discriminator
   |  +--ro remote-discr?             discriminator
   |  +--ro new-state?                state
   |  +--ro state-change-reason?      string
   |  +--ro time-in-previous-state?   string
   |  +--ro dest-addr?                inet:ip-address
   |  +--ro source-addr?              inet:ip-address
   |  +--ro session-index?            uint32
   |  +--ro session-type?             bfd-session-type
   |  +--ro ldp-fec?                  inet:ip-prefix
   |  +--ro source-port?              inet:port-number
   +---n bfd-lag-notification
      +--ro local-discr?              discriminator
      +--ro remote-discr?             discriminator
      +--ro new-state?                state
      +--ro state-change-reason?      string
      +--ro time-in-previous-state?   string
      +--ro dest-addr?                inet:ip-address
      +--ro source-addr?              inet:ip-address
      +--ro session-index?            uint32
      +--ro session-type?             bfd-session-type
      +--ro lag-name?                 if:interface-ref
      +--ro member-link?              if:interface-ref

**Pull request merged**
