### PR TITLE
802.1Qcx Published Modules

### PR DESCRIPTION
**Pull request by MarcHolness**
Published YANG modules for IEEE 802.1Qcx (CFM YANG).

Clean Pyang compilation

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf  ../802/ieee802-types.yang
pyang --ietf -p ../802/ ieee802-dot1q-cfm-types.yang
pyang --ietf -p ../802/ ieee802-dot1q-cfm.yang
pyang --ietf -p ../802/ ieee802-dot1q-cfm-bridge.yang
pyang --ietf -p ../802/ ieee802-dot1q-cfm-alarm.yang

pyang --ietf -p ../802/ ieee802-dot1q-types.yang
pyang --ietf -p ../802/ ieee802-dot1q-bridge.yang
pyang --ietf -p ../802/ ieee802-dot1q-pb.yang
pyang --ietf -p ../802/ ieee802-dot1q-tpmr.yang
../802/ieee802-types.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
../802/ieee802-types.yang:2: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-types"
../802/ieee802-types.yang:20: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-cfm-types.yang
ieee802-dot1q-cfm-types.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-cfm-types.yang:4: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-cfm-types"
ieee802-dot1q-cfm-types.yang:24: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-cfm.yang
ieee802-dot1q-cfm.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-cfm.yang:4: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-cfm"
ieee802-dot1q-cfm.yang:35: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).
ieee802-dot1q-cfm.yang:241: warning: the module seems to use RFC 2119 keywords, but the required text from RFC 8174 is not found (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-cfm-bridge.yang
ieee802-dot1q-cfm-bridge.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-cfm-bridge.yang:4: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-cfm-bridge"
ieee802-dot1q-cfm-bridge.yang:34: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).
ieee802-dot1q-cfm-bridge.yang:171: warning: the module seems to use RFC 2119 keywords, but the required text from RFC 8174 is not found (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-cfm-alarm.yang
ieee802-dot1q-cfm-alarm.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-cfm-alarm.yang:4: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-cfm-alarm"
ieee802-dot1q-cfm-alarm.yang:31: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).
ieee802-dot1q-cfm-alarm.yang:63: warning: explicit config statement is ignored

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-types.yang
ieee802-dot1q-types.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-types.yang:2: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-types"
ieee802-dot1q-types.yang:22: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-bridge.yang
ieee802-dot1q-bridge.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-bridge.yang:2: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-bridge"
ieee802-dot1q-bridge.yang:38: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-pb.yang
ieee802-dot1q-pb.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-pb.yang:2: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-pb"
ieee802-dot1q-pb.yang:29: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-tpmr.yang
ieee802-dot1q-tpmr.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-tpmr.yang:2: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-tpmr"
ieee802-dot1q-tpmr.yang:29: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$

### CODE REVIEW

**Comment by MarcHolness** [comment]
Clean PYANG compile.

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf  ../802/ieee802-types.yang
pyang --ietf -p ../802/ ieee802-dot1q-cfm-types.yang
pyang --ietf -p ../802/ ieee802-dot1q-cfm.yang
pyang --ietf -p ../802/ ieee802-dot1q-cfm-bridge.yang
pyang --ietf -p ../802/ ieee802-dot1q-cfm-alarm.yang

pyang --ietf -p ../802/ ieee802-dot1q-types.yang
pyang --ietf -p ../802/ ieee802-dot1q-bridge.yang
pyang --ietf -p ../802/ ieee802-dot1q-pb.yang
pyang --ietf -p ../802/ ieee802-dot1q-tpmr.yang
../802/ieee802-types.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
../802/ieee802-types.yang:2: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-types"
../802/ieee802-types.yang:20: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-cfm-types.yang
ieee802-dot1q-cfm-types.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-cfm-types.yang:4: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-cfm-types"
ieee802-dot1q-cfm-types.yang:24: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-cfm.yang
ieee802-dot1q-cfm.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-cfm.yang:4: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-cfm"
ieee802-dot1q-cfm.yang:35: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).
ieee802-dot1q-cfm.yang:241: warning: the module seems to use RFC 2119 keywords, but the required text from RFC 8174 is not found (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-cfm-bridge.yang
ieee802-dot1q-cfm-bridge.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-cfm-bridge.yang:4: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-cfm-bridge"
ieee802-dot1q-cfm-bridge.yang:34: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).
ieee802-dot1q-cfm-bridge.yang:171: warning: the module seems to use RFC 2119 keywords, but the required text from RFC 8174 is not found (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-cfm-alarm.yang
ieee802-dot1q-cfm-alarm.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-cfm-alarm.yang:4: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-cfm-alarm"
ieee802-dot1q-cfm-alarm.yang:31: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).
ieee802-dot1q-cfm-alarm.yang:63: warning: explicit config statement is ignored

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-types.yang
ieee802-dot1q-types.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-types.yang:2: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-types"
ieee802-dot1q-types.yang:22: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-bridge.yang
ieee802-dot1q-bridge.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-bridge.yang:2: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-bridge"
ieee802-dot1q-bridge.yang:38: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-pb.yang
ieee802-dot1q-pb.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-pb.yang:2: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-pb"
ieee802-dot1q-pb.yang:29: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$ pyang --ietf -p ../802/ ieee802-dot1q-tpmr.yang
ieee802-dot1q-tpmr.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
ieee802-dot1q-tpmr.yang:2: warning: RFC 8407: 4.9: namespace value should be "urn:ietf:params:xml:ns:yang:ieee802-dot1q-tpmr"
ieee802-dot1q-tpmr.yang:29: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing (see pyang --ietf-help for details).

mholness@ONW-MHOLNESS-02 MINGW32 /c/GitHub/MarcHolness/yang/standard/ieee/published/802.1 (master)
$

**Review by einarnn — APPROVED** [review]

**Comment by einarnn** [comment]
@MarcHolness, these changes broke the CI checks. Can you please take a look at the errors at:

> https://travis-ci.org/github/YangModels/yang/builds/729764192

...and resubmit the PR once fixed?

Cheers,

Einar

**Comment by MarcHolness** [comment]
Hi Einar,

I’ve been trying to debug this, and I don’t understand why these errors are occurring.

When I analyze the errors, shown below:

  *   I made no changes to any of the modules found in the directories with the errors
  *   In directory standard/ieee/draft/802.1/Qcw
     *   There is ieee802-dot1q-types.yang defined, and within it, there is a type-of-operation identity. So, I don’t understand why there is an error in line 988.
     *   Also within that same ieee802-dot1q-types.yang module, there is a base-gate-control-entries grouping defined. So, I don’t understand why there is an error in line 989.
     *   There is ieee802-types.yang defined, and within it, there is a rational-grouping grouping defined. So, I don’t understand why there is an errors on lines 991-996.
     *   Same story as for the errors on lines 1000-1011.


[cid:image002.jpg@01D698C4.157A8010]


As a result, I can’t figure out what I need to change.

Somehow, I think the compilation is not taking the correct version of ieee802-dot1q-types.yang and ieee802-types.yang. I have made changes to those YANG modules, as part of the Qcx project. Those versions do not include the types needed by the modules found in Qcw. Note: These directors are in the draft directory branch where we run parallel projects making changes to YANG modules.

I need some direction from you experts on this one.

Regards,

Marc.

**Comment by miroslavKovacPantheon** [comment]
Hello Marc,

I have reviewed your files and found the following problem. The command that is executed in here is as an example the following one

> pyang --verbose -p . -p /home/travis/build/YangModels/yang/standard/ieee/../ietf/RFC/ -p /home/travis/build/YangModels/yang/standard/ieee/draft/802 -p /home/travis/build/YangModels/yang/standard/ieee/published/802 -p /home/travis/build/YangModels/yang/standard/ieee/published/802.1  -p ../Qcr ieee802-dot1q-sched.yang

the same thing that will be described in following lines applies to others as well.

so when module ieee802-dot1q-sched.yang is being parsed with pyang and comes to import ieee802-dot1q-types it will search through all the directories with -p option. While it is true that you have 'type-of-operation' in yang/standard/ieee/draft/802.1/Qcw/ieee802-dot1q-types.yang of revision 2018-03-07 but it is missing in yang/standard/ieee/draft/802.1/Qcz/ieee802-dot1q-types.yang of revision 2018-08-10 and also in yang/standard/ieee/published/802.1/ieee802-dot1q-types.yang of revision 2020-06-04.

You might say that pyang is taking wrong revision in here but what is right? Since there is no given revision in the yang module itself when importing module, most of the yang validators in this kind of situation will take the latest revision and that is why we are missing this. I did not check for all the errors but I am guessing that this is going to be problem everywhere.

What you can do in this situation is create check.sh file for each directory since you have multiple same yang files used in different locations differently and give them correct -p options for parsing the file. -p is used to give the pyang path where he is suppose to search for the modules that would be imported or included by the parent modules.

I hope this help you to solve this issue and thank you for contributing.

Regards,
Miroslav Kovac

**Comment by MarcHolness** [comment]
Thanks Miroslav.

I understand. This makes sense.

As a bit of context. Perhaps you may find interesting …

  *   In IEEE, we have multiple parallel YANG projects (with different timelines and scope).
  *   Projects that are in progress (i.e., not ratified) are in our “draft” branch. Once a project is ratified, the YANG modules get promoted to the “published” branch.
  *   The active projects that are in the “draft” branch have their own project specific folders. These projects may be concurrently making changes to some of the common types modules (e.g., ieee802-dot1q-types.yang and ieee802-types.yang). These projects should have a local copy of these types in the project specific folder, if they make a change to these common type modules. However not all of these active projects will be making changes to these common type modules.

[cid:image002.jpg@01D69B44.1C5A7520]

  *   Okay, so, PYANG is getting confused as to which common type module to use. Or rather, the check.sh file is giving confusing instructions to PYANG.
  *   So, we may need per project check.sh files to fix this.

I’m just providing this context, in the event there is a better way. Maybe (??), we [IEEE], could use a different GitHub structure of  the ieee branch, to obviate this problem. I’ll give this some thought, and take it back to IEEE.

Regards,

Marc.

**Pull request merged**
