### PR TITLE
Add huawei yang modules 

### PR DESCRIPTION
**Pull request by hwRouterYangAdmin**
Add huawei yang models as submodel in directory of vendor
while modifying .travis.yml which call check_modules.sh

### CODE REVIEW

**Comment by tnadeau** [comment]
I think you forgot to push the ./vendor/huawei/check-models.sh file.  This is why the CI run is failing. Please amend the pull request with that file or withdraw/re-submit

**Comment by hwRouterYangAdmin** [comment]
i have push check-modules.sh file , and i am puzzled .the file link 
 https://github.com/Huawei/yang/tree/6be5d55471b8e144b605d40ba9e54035e9f95e12

**Comment by tnadeau** [comment]
You keep pulling a fork from your own Huawei branch. You need to start with the YangModels/Yang
and fork that. Make the changes, and then go back and do a pull request on the base repo.

	—Tom

**Comment by tnadeau** [comment]
Also, there is no need to add the IETF subdirectory; those files are present in the other part of the repo, so you should refer to them that way or your compilation will fail. Look at the other check.sh files and you will see the includes for pyang.

At this point, if it is easier for me to do your initial commit just let me know. I want to get you going here without the initial setup being too frustrating.

—Tom

**Comment by tnadeau** [comment]
A bunch of additions need to be made to this pull request, so it is simpler to create a new one from scratch with those additions, so I am closing this one.  Please push a new pull request and I will review ASAP or let me know if you still need help and I can just commit all the files for you.

**Pull request closed without merging**
