### PR TITLE
yc.o sync

### PR DESCRIPTION
**Pull request by xorrkaz**

### CODE REVIEW

**Review by einarnn — APPROVED** [review]

**Review by einarnn — DISMISSED** [review]

**Comment by einarnn** [comment]
@xorrkaz, there are a bunch of errors in the IETF content. Will you be looking at those?

**Comment by xorrkaz** [comment]
I am watching.  The problem is missing IANA modules.  The IANA sync job is running, and I saw one leak out recently.  I don't know why the rest are not.  If they don't get pushed before 121, I'll spend some time there sorting it.

**Comment by xorrkaz** [comment]
Ah, actually, I lied @einarnn.  The modules _do_ exist in the repo.  Your search path is wrong.  The IANA modules are spread between extracted and standard, but the search path in the failing job is `/home/runner/work/yang/yang/standard/ieee/published/`.  Can you expand the path to cover all module locations?

**Comment by einarnn** [comment]
@xorrkaz, it would be better if whoever is committing changes that broke the check scripts als fixed the check scripts as part of their commit. Was this broken by this commit or by a different one?

**Comment by xorrkaz** [comment]
It's not a question of a commit.  The IANA modules are now automatically updated in their own directory.  My other PR fixed looking for those.  _However_, in the case of these IANA SSH modules, their repo still refers to the drafts and not the RFCs.  Therefore, they aren't being added to the `standard/iana` directory.  I'll try and figure out when/how those get updated with IANA while I'm at the 121 meeting.

**Comment by xorrkaz** [comment]
I spoke with Sabrina from IANA, and she said the SSH modules are pending a review from Kent Watsen.  Once that clears, they should be fully published, and the `pyang` parsing should succeed.

**Review by einarnn — APPROVED** [review]

**Pull request merged**
