### PR TITLE
Add huawei submodule 

### PR DESCRIPTION
**Pull request by hwRouterYangAdmin**
Add huawei yang files as submodule of yang modules , and the repo is  https://github.com/Huawei/yang.git

### CODE REVIEW

**Comment by tnadeau** [comment]
Before we merge this, can you please update the top level .travis.yml file so that it calls the check.sh script for the Huawei subdir? You will need to copy in a stub of the check.sh file to set the stage for future commits. You can keep it blank, just make sure it returns 0 so that the CI runs complete successfully.

**Comment by hwRouterYangAdmin** [comment]
where is the top level .travis.yml file ?

**Comment by tnadeau** [comment]
https://github.com/YangModels/yang/blob/master/.travis.yml <https://github.com/YangModels/yang/blob/master/.travis.yml>

**Comment by hwRouterYangAdmin** [comment]
oh ,we have a similar  pyang check scripts,   , https://github.com/Huawei/yang/blob/master/network-router/check-models.sh,

**Comment by tnadeau** [comment]
Cool. That is fine. We just have used the same model for the check.sh scripts simply because
Einar and I have basically written/maintained them so consistency made it easier. If you want to
use your own checks that is cool just please make sure they are called from the travis file. 

	-_Tom

**Comment by hwRouterYangAdmin** [comment]
OK. We'll make sure that yang files to be uploaded have passed pyang check with no errors or warnings.

**Comment by tnadeau** [comment]
Can you withdraw this merge request and amend it with the updated travis CI file mods and the check.sh?  I'll merge this right away if you can.  If you need help with those two things, let me know and I can help.

**Comment by hwRouterYangAdmin** [comment]
where should i update travis CI file, i mean in which folder , in  the  https://github.com/Huawei/yang ?

**Comment by tnadeau** [comment]
What you need to do is create a fork of the https://github.com/YangModels/yang <https://github.com/YangModels/yang>

	Goto the page, click on fork at the top right. You have to be logged in too. That will fork a branch of the master repo 
for you.  Then go into there and create the new ../vendor/huawei directory and copy your README file.  Copy in
your pyang checks in there too. Then edit the top level .travis.yml file to call that.  Run it and make sure it works 
too!  Once that works, go back to the git webpage and select “create pull request”.  It usually selects the
correct from->to options from the last private repo you were working on. 

	—Tom

**Comment by hwRouterYangAdmin** [comment]
oh, i see. i'll update the .travis.yml  in my fork branch soon, just like bbf .Thanks

**Pull request closed without merging**
