### PR TITLE
Update Interface-VLAN and add Interface-Ext draft and associated YANG modules

### PR DESCRIPTION
**Pull request by rgwilton**
Updated an existing draft and added a new draft.  Also fixed a no break whitespace character issue in the XML source file.

### CODE REVIEW

**Comment by tnadeau** [comment]
Did you recompile this with pyang --ietf ?

**Comment by rgwilton** [comment]
No, not on the repository itself.

But all of the modules have been checked with pyang in my development 
directory.  They are clean.

One potential issue is that the YANG modules in 
experimental/ietf/interface-vlan/ have a dependency on one of the 
modules in experimental/ietf/interface-extensions/.  Is that going to be 
a problem?

**Comment by tnadeau** [comment]
One of our goals (we have very few) is to keep the repo building cleanly - at least as much as possible. We want to let people depend on the repo for functional models.

	—Tom

**Comment by tnadeau** [comment]
In the future when doing a pull request, please post the pyang output.

**Comment by rgwilton** [comment]
The only warning is for dot1q-types.yang because it is under an ieee namespace not ietf, otherwise all compile cleanly without warnings or errors.


sjc-ads-5101:yang$ pyang --ietf -f tree -p standard/ietf/RFC experimental/ietf/INTERFACE-EXTENSIONS/interfaces-common.yang 
module: interfaces-common
augment /if:interfaces/if:interface:
   +--rw bandwidth?   uint64
augment /if:interfaces/if:interface:
   +--rw carrier-delay
      +--rw down?   uint32
      +--rw up?     uint32
augment /if:interfaces/if:interface:
   +--rw dampening!
      +--rw half-life?           uint32
      +--rw reuse?               uint32
      +--rw suppress?            uint32
      +--rw max-suppress-time?   uint32
augment /if:interfaces/if:interface:
   +--rw encapsulation
      +--rw (encaps-type)?
augment /if:interfaces/if:interface:
   +--rw loopback?   identityref
augment /if:interfaces/if:interface:
   +--rw l2-mtu?   uint16 {configurable-l2-mtu}?
   +--rw l3-mtu?   uint16 {configurable-l3-mtu}?
augment /if:interfaces/if:interface:
   +--rw parent-interface?   if:interface-ref
augment /if:interfaces/if:interface:
   +--rw transport-layer?   enumeration
   


sjc-ads-5101:yang$ pyang --ietf -f tree -p standard/ietf/RFC experimental/ietf/INTERFACE-EXTENSIONS/interfaces-ethernet-like.yang 
module: interfaces-ethernet-like
augment /if:interfaces/if:interface:
   +--rw ethernet-like
      +--rw mac-address?   yang:mac-address
augment /if:interfaces-state/if:interface:
   +--ro ethernet-like
      +--ro mac-address?       yang:mac-address
      +--ro bia-mac-address?   yang:mac-address
sjc-ads-5101:yang$ 



sjc-ads-5101:yang$ pyang --ietf -f tree -p standard/ietf/RFC:experimental/ietf/INTERFACE-EXTENSIONS:experimental/ietf/INTERFACE-VLAN experimental/ietf/INTERFACE-VLAN/dot1q-types.yang 
experimental/ietf/INTERFACE-VLAN/dot1q-types.yang:2: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:dot1q-types"


sjc-ads-5101:yang$ pyang --ietf -f tree -p standard/ietf/RFC:experimental/ietf/INTERFACE-EXTENSIONS:experimental/ietf/INTERFACE-VLAN experimental/ietf/INTERFACE-VLAN/if-l3-vlan.yang 
module: if-l3-vlan
augment /if:interfaces/if:interface/if-cmn:encapsulation/if-cmn:encaps-type:
   +--:(vlan)
      +--rw vlan
         +--rw tags
            +--rw tag* [index]
               +--rw index        uint8
               +--rw dot1q-tag
                  +--rw tag-type    dot1q-tag-type
                  +--rw vlan-id     dot1q-vlan-id


sjc-ads-5101:yang$ pyang --ietf -f tree -p standard/ietf/RFC:experimental/ietf/INTERFACE-EXTENSIONS:experimental/ietf/INTERFACE-VLAN experimental/ietf/INTERFACE-VLAN/flexible-encapsulation.yang 
module: flexible-encapsulation
augment /if:interfaces/if:interface/if-cmn:encapsulation/if-cmn:encaps-type:
   +--:(flexible) {flexible-encapsulation-rewrites}?
      +--rw flexible
         +--rw match
         |  +--rw (match-type)
         |     +--:(default)
         |     |  +--rw default?           empty
         |     +--:(untagged)
         |     |  +--rw untagged?          empty
         |     +--:(priority-tagged)
         |     |  +--rw priority-tagged
         |     |     +--rw tag-type?   dot1q:dot1q-tag-type
         |     +--:(vlan-tagged)
         |        +--rw vlan-tagged
         |           +--rw tag* [index]
         |           |  +--rw index        uint8
         |           |  +--rw dot1q-tag
         |           |     +--rw tag-type    dot1q-tag-type
         |           |     +--rw vlan-id     union
         |           +--rw match-exact-tags?   empty
         +--rw rewrite {flexible-rewrites}?
            +--rw (direction)?
               +--:(symmetrical)
               |  +--rw symmetrical
               |     +--rw tag-rewrite {tag-rewrites}?
               |        +--rw pop-tags?    uint8
               |        +--rw push-tags* [index]
               |           +--rw index        uint8
               |           +--rw dot1q-tag
               |              +--rw tag-type    dot1q-tag-type
               |              +--rw vlan-id     dot1q-vlan-id
               +--:(asymmetrical) {asymmetric-rewrites}?
                  +--rw ingress
                  |  +--rw tag-rewrite {tag-rewrites}?
                  |     +--rw pop-tags?    uint8
                  |     +--rw push-tags* [index]
                  |        +--rw index        uint8
                  |        +--rw dot1q-tag
                  |           +--rw tag-type    dot1q-tag-type
                  |           +--rw vlan-id     dot1q-vlan-id
                  +--rw egress
                     +--rw tag-rewrite {tag-rewrites}?
                        +--rw pop-tags?    uint8
                        +--rw push-tags* [index]
                           +--rw index        uint8
                           +--rw dot1q-tag
                              +--rw tag-type    dot1q-tag-type
                              +--rw vlan-id     dot1q-vlan-id



sjc-ads-5101:yang$ pyang --ietf -f tree -p standard/ietf/RFC:experimental/ietf/INTERFACE-EXTENSIONS:experimental/ietf/INTERFACE-VLAN experimental/ietf/INTERFACE-VLAN/l2-bpdu-filtering.yang 
module: l2-bpdu-filtering
augment /if:interfaces/if:interface:
   +--rw bpdu
      +--rw filtering?   enumeration {bpdu-filtering}?

Thanks,
Rob

**Pull request merged**
