### PR TITLE
add EPON module and rename the PSE module

### PR DESCRIPTION
**Pull request by yanzhuang**

### CODE REVIEW

**Comment by tnadeau** [comment]
Please update the files to pass the travis CI tests that are failing.

**Comment by yanzhuang** [comment]
Hi Thomas, do you know why it fails? any error in the file or the format?

I just read the Build#243, for 802.3, it says :
"
Checking modules with pyang in directory experimental/ieee/802.3: 

Checking yang files in 802.3

pyang --verbose -p ../../../standard/ietf/RFC/ -p ../../../standard/ieee/draft/ -p ../../../standard/ieee/802.1/draft/ *.yang
"
in last sentence, should it be "../../standard/ieee/802.3/draft/*.yang"?
or it has nth. to do with this failure check...

Thanks.

**Comment by tnadeau** [comment]
I was able to repair the script - there was an error in there that wasn’t manifesting itself for some reason. 
However, I now have a compilation error on the files. I’ve asked Einar to take a look as he applied the patches.

	—Tom

**Comment by yanzhuang** [comment]
Thanks, Tom. Please let me know what i can do to fix it.

发件人: thomas d. nadeau [mailto:notifications@github.com]
发送时间: 2017年6月14日 2:13
收件人: YangModels/yang
抄送: Zhuangyan (Yan); Author
主题: Re: [YangModels/yang] add EPON module and rename the PSE module (#164)


I was able to repair the script - there was an error in there that wasn’t manifesting itself for some reason.
However, I now have a compilation error on the files. I’ve asked Einar to take a look as he applied the patches.

—Tom

**Comment by tnadeau** [comment]
I have merged the conflicts into the master branch but you did not include a check.sh that the travis CI will run. That now must be added.

**Pull request merged**
