### PR TITLE
Minor updates to XR-specific README.md

### PR DESCRIPTION
**Pull request by einarnn**
Added cisco.com links for more documentation on how to use YANG models on Cisco platforms, etc.

### CODE REVIEW

**Comment by tnadeau** [comment]
I am thinking of starting a slack channel/group for those working on the Yang models. I guess an alternative is an IRC channel. Any thoughts?

	—Tom

**Comment by einarnn** [comment]
Slack or IRC works fine for me.

**Comment by yamrock** [comment]
Hi, Was this Slack channel created?

**Comment by tnadeau** [comment]
No worry. I must have missed this. I will add this shortly.

	—Tom

**Comment by tnadeau** [comment]
I have created a new slack channel/group here:

To Subscribe and Browse Click Here <https://yangmodels.slack.com/>

**Comment by einarnn** [comment]
It says that unless you have an @lucidvision.com email, you need an invite...?

**Comment by tnadeau** [comment]
thats odd. let me check later this afternoon...

**Comment by tnadeau** [comment]
There are only 2 modes of operation for allowing joining onto slack "teams" - by domain(s) or by invitation only. Please try the link now. It will send approvals to me to allow people to join. Ill expand that approvals list to the rep commiters so that we are as responsive as possible. https://yangmodels.slack.com/signup

**Comment by einarnn** [comment]
"Ask your administrator to send you an invitation"

**Comment by tnadeau** [comment]
It looks like I have to get a paid Slack account to allow non-restricted users to join. I’ll sort this out in the near future…

	—Tom

**Pull request merged**
